global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # !!!!!!!!!!!!! és a másik ahol van

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080']
